# Generated by Django 5.0.7 on 2024-07-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('brend', models.CharField(max_length=25)),
                ('chegrma', models.CharField(max_length=11, null=True)),
                ('mavjud', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Fodlanuvchi',
        ),
    ]
