# Generated by Django 5.0.7 on 2024-07-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_maxsulot_delete_fodlanuvchi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('yonaish', models.CharField(max_length=25)),
                ('daraja', models.CharField(max_length=11)),
                ('davomiyligi', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Maxsulot',
        ),
    ]
