# Generated by Django 5.0.7 on 2024-07-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_kurs_delete_maxsulot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Futbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tranfer_narx', models.CharField(max_length=25)),
                ('yosh', models.CharField(max_length=11)),
                ('klub', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Kurs',
        ),
    ]
