# Generated by Django 5.0.7 on 2024-07-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_futbol_delete_kurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moshina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rusum', models.CharField(max_length=25)),
                ('kompaniya', models.CharField(max_length=30)),
                ('raqami', models.SmallIntegerField()),
                ('yili', models.DateTimeField()),
                ('rangi', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='futbol',
            name='yosh',
            field=models.SmallIntegerField(),
        ),
    ]
