# Generated by Django 5.0.7 on 2024-07-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_moshina_alter_futbol_yosh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('yonalsh', models.CharField(max_length=25)),
                ('yonalish', models.CharField(max_length=25)),
                ('daraja', models.SmallIntegerField()),
                ('davomiyligi', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('brend', models.CharField(max_length=25)),
                ('chegrma', models.SmallIntegerField(null=True)),
                ('mavjud', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='futbol',
            name='tranfer_narx',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='moshina',
            name='yili',
            field=models.DateField(),
        ),
    ]
