# Generated by Django 5.0.7 on 2024-07-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_kurs_maxsulot_alter_futbol_tranfer_narx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('muallif', models.SmallIntegerField()),
                ('janr', models.CharField(max_length=15)),
                ('beti', models.SmallIntegerField()),
            ],
        ),
    ]
