# Generated by Django 5.0.7 on 2024-07-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_kitob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kitob',
        ),
    ]
