# Generated by Django 5.0.7 on 2024-07-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_delete_kitob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('mualif', models.SmallIntegerField()),
                ('janr', models.CharField(max_length=10)),
                ('beti', models.SmallIntegerField()),
            ],
        ),
    ]
