# Generated by Django 5.0.7 on 2024-07-17 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_kitob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kitob',
        ),
    ]
