# Generated by Django 5.0.7 on 2024-07-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_delete_kitob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='yonalsh',
        ),
    ]
