# Generated by Django 5.0.7 on 2024-07-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('mualif', models.SmallIntegerField()),
                ('janr', models.CharField(max_length=10)),
                ('beti', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kutibxonachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('yosh', models.SmallIntegerField()),
                ('userNAME', models.CharField(max_length=30)),
                ('password', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('t_yili', models.SmallIntegerField()),
                ('trik', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('h_raqami', models.SmallIntegerField()),
                ('sinf', models.SmallIntegerField()),
            ],
        ),
    ]
