# Generated by Django 5.0.7 on 2024-07-17 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kutubxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olgan_sana', models.DateTimeField()),
                ('qaytarish_sana', models.DateField()),
                ('qaytardimi', models.BooleanField()),
                ('kitob_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.kitob')),
                ('kutubxonachi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.kutibxonachi')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.oquvchi')),
            ],
        ),
    ]
