# Generated by Django 5.0.7 on 2024-07-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_kutubxona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kutubxona',
            name='olgan_sana',
            field=models.DateField(),
        ),
    ]
