# Generated by Django 5.0.7 on 2024-07-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_alter_kutubxona_olgan_sana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muallif',
            old_name='t_yili',
            new_name='yoshi',
        ),
    ]
