# Generated by Django 5.0.7 on 2024-07-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('yonalish', models.CharField(max_length=25)),
                ('yoshi', models.SmallIntegerField()),
                ('fani', models.CharField(max_length=20)),
            ],
        ),
    ]
