# Generated by Django 5.0.7 on 2024-07-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oligoh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ustoz',
            name='fani',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
